apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.authsvc.type }}
  ports:
    - port: {{ .Values.service.authsvc.restPort }}
      name: rest
  selector:
    app: {{ .Chart.Name }}